-- MySQL Script generated by MySQL Workbench
-- Wed Jun 21 13:50:00 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_salve_raiz
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_salve_raiz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_salve_raiz` DEFAULT CHARACTER SET utf8 ;
USE `db_salve_raiz` ;

-- -----------------------------------------------------
-- Table `db_salve_raiz`.`tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_salve_raiz`.`tema` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  `tipo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_salve_raiz`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_salve_raiz`.`usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `usuario` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `foto` VARCHAR(255) NOT NULL,
  `tipo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_salve_raiz`.`postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_salve_raiz`.`postagem` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `texto` VARCHAR(400) NOT NULL,
  `data` DATE NOT NULL,
  `foto` VARCHAR(255) NOT NULL,
  `curtidas` INT NOT NULL,
  `tema_id` BIGINT NOT NULL,
  `usuario_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_postagem_tema_idx` (`tema_id` ASC) VISIBLE,
  INDEX `fk_postagem_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_postagem_tema`
    FOREIGN KEY (`tema_id`)
    REFERENCES `db_salve_raiz`.`tema` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_postagem_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `db_salve_raiz`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
